repos:
  - repo: https://github.com/pycqa/autoflake
    rev: v2.2.1  # Use the latest version
    hooks:
      - id: autoflake
        args: [
          --remove-all-unused-imports,
          --remove-unused-variables,
          --in-place,
          --recursive
        ]